/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const StakeholderRole = IDL.Variant({
  'economicBuyer' : IDL.Null,
  'blocker' : IDL.Null,
  'procurement' : IDL.Null,
  'champion' : IDL.Null,
  'technicalEvaluator' : IDL.Null,
});
export const EngagementLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'none' : IDL.Null,
  'medium' : IDL.Null,
});
export const Stakeholder = IDL.Record({
  'name' : IDL.Text,
  'role' : StakeholderRole,
  'lastContacted' : IDL.Int,
  'engagement' : EngagementLevel,
});
export const DealStage = IDL.Variant({
  'prospecting' : IDL.Null,
  'closedWon' : IDL.Null,
  'proposal' : IDL.Null,
  'negotiation' : IDL.Null,
  'qualification' : IDL.Null,
  'closedLost' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'activityPrior30Days' : IDL.Nat,
  'owner' : IDL.Text,
  'stakeholders' : IDL.Vec(Stakeholder),
  'name' : IDL.Text,
  'createdDate' : IDL.Int,
  'closeDatePushes' : IDL.Nat,
  'lastActivityDate' : IDL.Int,
  'expectedCloseDate' : IDL.Int,
  'stage' : DealStage,
  'notes' : IDL.Text,
  'account' : IDL.Text,
  'activityLast30Days' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const PipelineError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Nat,
});
export const PipelineResult = IDL.Variant({
  'ok' : Deal,
  'err' : PipelineError,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PipelineResult_1 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : PipelineError,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const RiskSignal = IDL.Record({
  'weight' : IDL.Float64,
  'code' : IDL.Text,
  'detail' : IDL.Text,
  'caption' : IDL.Text,
  'contribution' : IDL.Float64,
});
export const RiskBucket = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DealRisk = IDL.Record({
  'signals' : IDL.Vec(RiskSignal),
  'explanation' : IDL.Text,
  'dealId' : IDL.Nat,
  'score' : IDL.Float64,
  'recommendedAction' : IDL.Text,
  'topReason' : IDL.Text,
  'bucket' : RiskBucket,
  'explanationGeneratedAt' : IDL.Opt(IDL.Int),
});
export const PipelineResult_3 = IDL.Variant({
  'ok' : DealRisk,
  'err' : PipelineError,
});
export const ForecastBreakdown = IDL.Record({
  'key' : IDL.Text,
  'totalValue' : IDL.Nat,
  'weightedValue' : IDL.Nat,
  'caption' : IDL.Text,
  'dealCount' : IDL.Nat,
});
export const Forecast = IDL.Record({
  'low' : IDL.Nat,
  'byOwner' : IDL.Vec(ForecastBreakdown),
  'computedAt' : IDL.Int,
  'rationaleGeneratedAt' : IDL.Opt(IDL.Int),
  'high' : IDL.Nat,
  'byRiskBucket' : IDL.Vec(ForecastBreakdown),
  'byStage' : IDL.Vec(ForecastBreakdown),
  'confidenceLabel' : IDL.Text,
  'rangeBasis' : IDL.Text,
  'rationale' : IDL.Text,
  'naivePipeline' : IDL.Nat,
  'repCommitEstimate' : IDL.Nat,
  'mostLikely' : IDL.Nat,
});
export const PipelineResult_2 = IDL.Variant({
  'ok' : Forecast,
  'err' : PipelineError,
});
export const StageStats = IDL.Record({
  'totalValue' : IDL.Nat,
  'weightedValue' : IDL.Nat,
  'stage' : DealStage,
  'dealCount' : IDL.Nat,
  'avgDaysInStage' : IDL.Float64,
  'winRate' : IDL.Float64,
});
export const HistoricalBaseline = IDL.Record({
  'forecastErrorPct' : IDL.Float64,
  'overallWinRate' : IDL.Float64,
  'avgDealCycleDays' : IDL.Float64,
  'stageStats' : IDL.Vec(StageStats),
  'closedDealCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addStakeholder' : IDL.Func([IDL.Nat, Stakeholder], [PipelineResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDeal' : IDL.Func([Deal], [PipelineResult], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [PipelineResult_1], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'generateDealReasoning' : IDL.Func([IDL.Nat], [PipelineResult_3], []),
  'generateForecastRationale' : IDL.Func([], [PipelineResult_2], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBaseline' : IDL.Func([], [HistoricalBaseline], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
  'getDealReasoning' : IDL.Func([IDL.Nat], [IDL.Opt(DealRisk)], ['query']),
  'getForecast' : IDL.Func([], [Forecast], ['query']),
  'getForecastRationale' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'generatedAt' : IDL.Int, 'text' : IDL.Text }))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDealRisks' : IDL.Func([], [IDL.Vec(DealRisk)], ['query']),
  'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'resetSampleData' : IDL.Func([], [PipelineResult_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'storeAddStakeholder' : IDL.Func(
      [IDL.Nat, Stakeholder],
      [PipelineResult],
      [],
    ),
  'storeBaseline' : IDL.Func([], [HistoricalBaseline], []),
  'storeCreateDeal' : IDL.Func([Deal], [PipelineResult], []),
  'storeDeleteDeal' : IDL.Func([IDL.Nat], [PipelineResult_1], []),
  'storeGetDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], []),
  'storeListDeals' : IDL.Func([], [IDL.Vec(Deal)], []),
  'storeUpdateDeal' : IDL.Func([IDL.Nat, Deal], [PipelineResult], []),
  'storeUpdateStakeholder' : IDL.Func(
      [IDL.Nat, IDL.Nat, Stakeholder],
      [PipelineResult],
      [],
    ),
  'updateDeal' : IDL.Func([IDL.Nat, Deal], [PipelineResult], []),
  'updateStakeholder' : IDL.Func(
      [IDL.Nat, IDL.Nat, Stakeholder],
      [PipelineResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const StakeholderRole = IDL.Variant({
    'economicBuyer' : IDL.Null,
    'blocker' : IDL.Null,
    'procurement' : IDL.Null,
    'champion' : IDL.Null,
    'technicalEvaluator' : IDL.Null,
  });
  const EngagementLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'none' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Stakeholder = IDL.Record({
    'name' : IDL.Text,
    'role' : StakeholderRole,
    'lastContacted' : IDL.Int,
    'engagement' : EngagementLevel,
  });
  const DealStage = IDL.Variant({
    'prospecting' : IDL.Null,
    'closedWon' : IDL.Null,
    'proposal' : IDL.Null,
    'negotiation' : IDL.Null,
    'qualification' : IDL.Null,
    'closedLost' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'activityPrior30Days' : IDL.Nat,
    'owner' : IDL.Text,
    'stakeholders' : IDL.Vec(Stakeholder),
    'name' : IDL.Text,
    'createdDate' : IDL.Int,
    'closeDatePushes' : IDL.Nat,
    'lastActivityDate' : IDL.Int,
    'expectedCloseDate' : IDL.Int,
    'stage' : DealStage,
    'notes' : IDL.Text,
    'account' : IDL.Text,
    'activityLast30Days' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const PipelineError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Nat,
  });
  const PipelineResult = IDL.Variant({ 'ok' : Deal, 'err' : PipelineError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PipelineResult_1 = IDL.Variant({
    'ok' : IDL.Null,
    'err' : PipelineError,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const RiskSignal = IDL.Record({
    'weight' : IDL.Float64,
    'code' : IDL.Text,
    'detail' : IDL.Text,
    'caption' : IDL.Text,
    'contribution' : IDL.Float64,
  });
  const RiskBucket = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DealRisk = IDL.Record({
    'signals' : IDL.Vec(RiskSignal),
    'explanation' : IDL.Text,
    'dealId' : IDL.Nat,
    'score' : IDL.Float64,
    'recommendedAction' : IDL.Text,
    'topReason' : IDL.Text,
    'bucket' : RiskBucket,
    'explanationGeneratedAt' : IDL.Opt(IDL.Int),
  });
  const PipelineResult_3 = IDL.Variant({
    'ok' : DealRisk,
    'err' : PipelineError,
  });
  const ForecastBreakdown = IDL.Record({
    'key' : IDL.Text,
    'totalValue' : IDL.Nat,
    'weightedValue' : IDL.Nat,
    'caption' : IDL.Text,
    'dealCount' : IDL.Nat,
  });
  const Forecast = IDL.Record({
    'low' : IDL.Nat,
    'byOwner' : IDL.Vec(ForecastBreakdown),
    'computedAt' : IDL.Int,
    'rationaleGeneratedAt' : IDL.Opt(IDL.Int),
    'high' : IDL.Nat,
    'byRiskBucket' : IDL.Vec(ForecastBreakdown),
    'byStage' : IDL.Vec(ForecastBreakdown),
    'confidenceLabel' : IDL.Text,
    'rangeBasis' : IDL.Text,
    'rationale' : IDL.Text,
    'naivePipeline' : IDL.Nat,
    'repCommitEstimate' : IDL.Nat,
    'mostLikely' : IDL.Nat,
  });
  const PipelineResult_2 = IDL.Variant({
    'ok' : Forecast,
    'err' : PipelineError,
  });
  const StageStats = IDL.Record({
    'totalValue' : IDL.Nat,
    'weightedValue' : IDL.Nat,
    'stage' : DealStage,
    'dealCount' : IDL.Nat,
    'avgDaysInStage' : IDL.Float64,
    'winRate' : IDL.Float64,
  });
  const HistoricalBaseline = IDL.Record({
    'forecastErrorPct' : IDL.Float64,
    'overallWinRate' : IDL.Float64,
    'avgDealCycleDays' : IDL.Float64,
    'stageStats' : IDL.Vec(StageStats),
    'closedDealCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addStakeholder' : IDL.Func([IDL.Nat, Stakeholder], [PipelineResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDeal' : IDL.Func([Deal], [PipelineResult], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [PipelineResult_1], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'generateDealReasoning' : IDL.Func([IDL.Nat], [PipelineResult_3], []),
    'generateForecastRationale' : IDL.Func([], [PipelineResult_2], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBaseline' : IDL.Func([], [HistoricalBaseline], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
    'getDealReasoning' : IDL.Func([IDL.Nat], [IDL.Opt(DealRisk)], ['query']),
    'getForecast' : IDL.Func([], [Forecast], ['query']),
    'getForecastRationale' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'generatedAt' : IDL.Int, 'text' : IDL.Text }))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDealRisks' : IDL.Func([], [IDL.Vec(DealRisk)], ['query']),
    'listDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'resetSampleData' : IDL.Func([], [PipelineResult_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'storeAddStakeholder' : IDL.Func(
        [IDL.Nat, Stakeholder],
        [PipelineResult],
        [],
      ),
    'storeBaseline' : IDL.Func([], [HistoricalBaseline], []),
    'storeCreateDeal' : IDL.Func([Deal], [PipelineResult], []),
    'storeDeleteDeal' : IDL.Func([IDL.Nat], [PipelineResult_1], []),
    'storeGetDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], []),
    'storeListDeals' : IDL.Func([], [IDL.Vec(Deal)], []),
    'storeUpdateDeal' : IDL.Func([IDL.Nat, Deal], [PipelineResult], []),
    'storeUpdateStakeholder' : IDL.Func(
        [IDL.Nat, IDL.Nat, Stakeholder],
        [PipelineResult],
        [],
      ),
    'updateDeal' : IDL.Func([IDL.Nat, Deal], [PipelineResult], []),
    'updateStakeholder' : IDL.Func(
        [IDL.Nat, IDL.Nat, Stakeholder],
        [PipelineResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };