/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface Deal {
  'id' : bigint,
  'activityPrior30Days' : bigint,
  'owner' : string,
  'stakeholders' : Array<Stakeholder>,
  'name' : string,
  'createdDate' : bigint,
  'closeDatePushes' : bigint,
  'lastActivityDate' : bigint,
  'expectedCloseDate' : bigint,
  'stage' : DealStage,
  'notes' : string,
  'account' : string,
  'activityLast30Days' : bigint,
  'amount' : bigint,
}
export interface DealRisk {
  'signals' : Array<RiskSignal>,
  'explanation' : string,
  'dealId' : bigint,
  'score' : number,
  'recommendedAction' : string,
  'topReason' : string,
  'bucket' : RiskBucket,
  'explanationGeneratedAt' : [] | [bigint],
}
export type DealStage = { 'prospecting' : null } |
  { 'closedWon' : null } |
  { 'proposal' : null } |
  { 'negotiation' : null } |
  { 'qualification' : null } |
  { 'closedLost' : null };
export type EngagementLevel = { 'low' : null } |
  { 'high' : null } |
  { 'none' : null } |
  { 'medium' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Forecast {
  'low' : bigint,
  'byOwner' : Array<ForecastBreakdown>,
  'computedAt' : bigint,
  'rationaleGeneratedAt' : [] | [bigint],
  'high' : bigint,
  'byRiskBucket' : Array<ForecastBreakdown>,
  'byStage' : Array<ForecastBreakdown>,
  'confidenceLabel' : string,
  'rangeBasis' : string,
  'rationale' : string,
  'naivePipeline' : bigint,
  'repCommitEstimate' : bigint,
  'mostLikely' : bigint,
}
export interface ForecastBreakdown {
  'key' : string,
  'totalValue' : bigint,
  'weightedValue' : bigint,
  'caption' : string,
  'dealCount' : bigint,
}
export interface HistoricalBaseline {
  'forecastErrorPct' : number,
  'overallWinRate' : number,
  'avgDealCycleDays' : number,
  'stageStats' : Array<StageStats>,
  'closedDealCount' : bigint,
}
export type PipelineError = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : bigint };
export type PipelineResult = { 'ok' : Deal } |
  { 'err' : PipelineError };
export type PipelineResult_1 = { 'ok' : null } |
  { 'err' : PipelineError };
export type PipelineResult_2 = { 'ok' : Forecast } |
  { 'err' : PipelineError };
export type PipelineResult_3 = { 'ok' : DealRisk } |
  { 'err' : PipelineError };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type RiskBucket = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface RiskSignal {
  'weight' : number,
  'code' : string,
  'detail' : string,
  'caption' : string,
  'contribution' : number,
}
export interface StageStats {
  'totalValue' : bigint,
  'weightedValue' : bigint,
  'stage' : DealStage,
  'dealCount' : bigint,
  'avgDaysInStage' : number,
  'winRate' : number,
}
export interface Stakeholder {
  'name' : string,
  'role' : StakeholderRole,
  'lastContacted' : bigint,
  'engagement' : EngagementLevel,
}
export type StakeholderRole = { 'economicBuyer' : null } |
  { 'blocker' : null } |
  { 'procurement' : null } |
  { 'champion' : null } |
  { 'technicalEvaluator' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addStakeholder' : ActorMethod<[bigint, Stakeholder], PipelineResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDeal' : ActorMethod<[Deal], PipelineResult>,
  'deleteDeal' : ActorMethod<[bigint], PipelineResult_1>,
  'execute' : ActorMethod<[string], Result>,
  'generateDealReasoning' : ActorMethod<[bigint], PipelineResult_3>,
  'generateForecastRationale' : ActorMethod<[], PipelineResult_2>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBaseline' : ActorMethod<[], HistoricalBaseline>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeal' : ActorMethod<[bigint], [] | [Deal]>,
  'getDealReasoning' : ActorMethod<[bigint], [] | [DealRisk]>,
  'getForecast' : ActorMethod<[], Forecast>,
  'getForecastRationale' : ActorMethod<
    [],
    [] | [{ 'generatedAt' : bigint, 'text' : string }]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDealRisks' : ActorMethod<[], Array<DealRisk>>,
  'listDeals' : ActorMethod<[], Array<Deal>>,
  'resetSampleData' : ActorMethod<[], PipelineResult_1>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Replaces all pipeline state with the deterministic synthetic dataset.
   */
  'seedSampleData' : ActorMethod<[], undefined>,
  'storeAddStakeholder' : ActorMethod<[bigint, Stakeholder], PipelineResult>,
  'storeBaseline' : ActorMethod<[], HistoricalBaseline>,
  'storeCreateDeal' : ActorMethod<[Deal], PipelineResult>,
  'storeDeleteDeal' : ActorMethod<[bigint], PipelineResult_1>,
  'storeGetDeal' : ActorMethod<[bigint], [] | [Deal]>,
  'storeListDeals' : ActorMethod<[], Array<Deal>>,
  'storeUpdateDeal' : ActorMethod<[bigint, Deal], PipelineResult>,
  'storeUpdateStakeholder' : ActorMethod<
    [bigint, bigint, Stakeholder],
    PipelineResult
  >,
  'updateDeal' : ActorMethod<[bigint, Deal], PipelineResult>,
  'updateStakeholder' : ActorMethod<
    [bigint, bigint, Stakeholder],
    PipelineResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];