/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface Deal {
    id: bigint;
    activityPrior30Days: bigint;
    owner: string;
    stakeholders: Array<Stakeholder>;
    name: string;
    createdDate: bigint;
    closeDatePushes: bigint;
    lastActivityDate: bigint;
    expectedCloseDate: bigint;
    stage: DealStage;
    notes: string;
    account: string;
    activityLast30Days: bigint;
    amount: bigint;
}
export interface DealRisk {
    signals: Array<RiskSignal>;
    explanation: string;
    dealId: bigint;
    score: number;
    recommendedAction: string;
    topReason: string;
    bucket: RiskBucket;
    explanationGeneratedAt?: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Forecast {
    low: bigint;
    byOwner: Array<ForecastBreakdown>;
    computedAt: bigint;
    rationaleGeneratedAt?: bigint;
    high: bigint;
    byRiskBucket: Array<ForecastBreakdown>;
    byStage: Array<ForecastBreakdown>;
    confidenceLabel: string;
    rangeBasis: string;
    rationale: string;
    naivePipeline: bigint;
    repCommitEstimate: bigint;
    mostLikely: bigint;
}
export interface ForecastBreakdown {
    key: string;
    totalValue: bigint;
    weightedValue: bigint;
    caption: string;
    dealCount: bigint;
}
export interface HistoricalBaseline {
    forecastErrorPct: number;
    overallWinRate: number;
    avgDealCycleDays: number;
    stageStats: Array<StageStats>;
    closedDealCount: bigint;
}
export type PipelineError = {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: bigint;
};
export type PipelineResult = {
    __kind__: "ok";
    ok: Deal;
} | {
    __kind__: "err";
    err: PipelineError;
};
export type PipelineResult_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: PipelineError;
};
export type PipelineResult_2 = {
    __kind__: "ok";
    ok: Forecast;
} | {
    __kind__: "err";
    err: PipelineError;
};
export type PipelineResult_3 = {
    __kind__: "ok";
    ok: DealRisk;
} | {
    __kind__: "err";
    err: PipelineError;
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RiskSignal {
    weight: number;
    code: string;
    detail: string;
    caption: string;
    contribution: number;
}
export interface StageStats {
    totalValue: bigint;
    weightedValue: bigint;
    stage: DealStage;
    dealCount: bigint;
    avgDaysInStage: number;
    winRate: number;
}
export interface Stakeholder {
    name: string;
    role: StakeholderRole;
    lastContacted: bigint;
    engagement: EngagementLevel;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum DealStage {
    prospecting = "prospecting",
    closedWon = "closedWon",
    proposal = "proposal",
    negotiation = "negotiation",
    qualification = "qualification",
    closedLost = "closedLost"
}
export enum EngagementLevel {
    low = "low",
    high = "high",
    none = "none",
    medium = "medium"
}
export enum RiskBucket {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum StakeholderRole {
    economicBuyer = "economicBuyer",
    blocker = "blocker",
    procurement = "procurement",
    champion = "champion",
    technicalEvaluator = "technicalEvaluator"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addStakeholder(dealId: bigint, stakeholder: Stakeholder): Promise<PipelineResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDeal(deal: Deal): Promise<PipelineResult>;
    deleteDeal(id: bigint): Promise<PipelineResult_1>;
    execute(qJson: string): Promise<Result>;
    generateDealReasoning(dealId: bigint): Promise<PipelineResult_3>;
    generateForecastRationale(): Promise<PipelineResult_2>;
    getApiDoc(): Promise<string>;
    getBaseline(): Promise<HistoricalBaseline>;
    getCallerUserRole(): Promise<UserRole>;
    getDeal(id: bigint): Promise<Deal | null>;
    getDealReasoning(dealId: bigint): Promise<DealRisk | null>;
    getForecast(): Promise<Forecast>;
    getForecastRationale(): Promise<{
        generatedAt: bigint;
        text: string;
    } | null>;
    isCallerAdmin(): Promise<boolean>;
    listDealRisks(): Promise<Array<DealRisk>>;
    listDeals(): Promise<Array<Deal>>;
    resetSampleData(): Promise<PipelineResult_1>;
    schema(): Promise<string>;
    /**
     * / Replaces all pipeline state with the deterministic synthetic dataset.
     */
    seedSampleData(): Promise<void>;
    storeAddStakeholder(dealId: bigint, stakeholder: Stakeholder): Promise<PipelineResult>;
    storeBaseline(): Promise<HistoricalBaseline>;
    storeCreateDeal(deal: Deal): Promise<PipelineResult>;
    storeDeleteDeal(id: bigint): Promise<PipelineResult_1>;
    storeGetDeal(id: bigint): Promise<Deal | null>;
    storeListDeals(): Promise<Array<Deal>>;
    storeUpdateDeal(id: bigint, deal: Deal): Promise<PipelineResult>;
    storeUpdateStakeholder(dealId: bigint, stakeholderIndex: bigint, stakeholder: Stakeholder): Promise<PipelineResult>;
    updateDeal(id: bigint, deal: Deal): Promise<PipelineResult>;
    updateStakeholder(dealId: bigint, stakeholderIndex: bigint, stakeholder: Stakeholder): Promise<PipelineResult>;
}
import type { Cell as _Cell, Deal as _Deal, DealRisk as _DealRisk, DealStage as _DealStage, EngagementLevel as _EngagementLevel, Error as _Error, Forecast as _Forecast, ForecastBreakdown as _ForecastBreakdown, HistoricalBaseline as _HistoricalBaseline, PipelineError as _PipelineError, PipelineResult as _PipelineResult, PipelineResult_1 as _PipelineResult_1, PipelineResult_2 as _PipelineResult_2, PipelineResult_3 as _PipelineResult_3, Result as _Result, Result__1 as _Result__1, RiskBucket as _RiskBucket, RiskSignal as _RiskSignal, StageStats as _StageStats, Stakeholder as _Stakeholder, StakeholderRole as _StakeholderRole, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addStakeholder(arg0: bigint, arg1: Stakeholder): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addStakeholder(arg0, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStakeholder(arg0, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDeal(arg0: Deal): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeal(to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeal(to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDeal(arg0: bigint): Promise<PipelineResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeal(arg0);
                return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeal(arg0);
            return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateDealReasoning(arg0: bigint): Promise<PipelineResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.generateDealReasoning(arg0);
                return from_candid_PipelineResult_3_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateDealReasoning(arg0);
            return from_candid_PipelineResult_3_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateForecastRationale(): Promise<PipelineResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.generateForecastRationale();
                return from_candid_PipelineResult_2_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateForecastRationale();
            return from_candid_PipelineResult_2_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getBaseline(): Promise<HistoricalBaseline> {
        if (this.processError) {
            try {
                const result = await this.actor.getBaseline();
                return from_candid_HistoricalBaseline_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBaseline();
            return from_candid_HistoricalBaseline_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeal(arg0: bigint): Promise<Deal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeal(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeal(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDealReasoning(arg0: bigint): Promise<DealRisk | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDealReasoning(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDealReasoning(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForecast(): Promise<Forecast> {
        if (this.processError) {
            try {
                const result = await this.actor.getForecast();
                return from_candid_Forecast_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForecast();
            return from_candid_Forecast_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForecastRationale(): Promise<{
        generatedAt: bigint;
        text: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForecastRationale();
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForecastRationale();
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDealRisks(): Promise<Array<DealRisk>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDealRisks();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDealRisks();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeals();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeals();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetSampleData(): Promise<PipelineResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSampleData();
                return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSampleData();
            return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async storeAddStakeholder(arg0: bigint, arg1: Stakeholder): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.storeAddStakeholder(arg0, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeAddStakeholder(arg0, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeBaseline(): Promise<HistoricalBaseline> {
        if (this.processError) {
            try {
                const result = await this.actor.storeBaseline();
                return from_candid_HistoricalBaseline_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeBaseline();
            return from_candid_HistoricalBaseline_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeCreateDeal(arg0: Deal): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.storeCreateDeal(to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeCreateDeal(to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeDeleteDeal(arg0: bigint): Promise<PipelineResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.storeDeleteDeal(arg0);
                return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeDeleteDeal(arg0);
            return from_candid_PipelineResult_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeGetDeal(arg0: bigint): Promise<Deal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.storeGetDeal(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeGetDeal(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeListDeals(): Promise<Array<Deal>> {
        if (this.processError) {
            try {
                const result = await this.actor.storeListDeals();
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeListDeals();
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeUpdateDeal(arg0: bigint, arg1: Deal): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.storeUpdateDeal(arg0, to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeUpdateDeal(arg0, to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async storeUpdateStakeholder(arg0: bigint, arg1: bigint, arg2: Stakeholder): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.storeUpdateStakeholder(arg0, arg1, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeUpdateStakeholder(arg0, arg1, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeal(arg0: bigint, arg1: Deal): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeal(arg0, to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeal(arg0, to_candid_Deal_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStakeholder(arg0: bigint, arg1: bigint, arg2: Stakeholder): Promise<PipelineResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStakeholder(arg0, arg1, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStakeholder(arg0, arg1, to_candid_Stakeholder_n5(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PipelineResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_DealRisk_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealRisk): DealRisk {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_DealStage_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DealStage): DealStage {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Deal_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Deal): Deal {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EngagementLevel_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EngagementLevel): EngagementLevel {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Forecast_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Forecast): Forecast {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_HistoricalBaseline_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoricalBaseline): HistoricalBaseline {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineError_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineError): PipelineError {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineResult_1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineResult_1): PipelineResult_1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineResult_2_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineResult_2): PipelineResult_2 {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineResult_3_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineResult_3): PipelineResult_3 {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PipelineResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PipelineResult): PipelineResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RiskBucket_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskBucket): RiskBucket {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_StageStats_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StageStats): StageStats {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_StakeholderRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StakeholderRole): StakeholderRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Stakeholder_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stakeholder): Stakeholder {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Deal]): Deal | null {
    return value.length === 0 ? null : from_candid_Deal_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DealRisk]): DealRisk | null {
    return value.length === 0 ? null : from_candid_DealRisk_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        generatedAt: bigint;
        text: string;
    }]): {
    generatedAt: bigint;
    text: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityPrior30Days: bigint;
    owner: string;
    stakeholders: Array<_Stakeholder>;
    name: string;
    createdDate: bigint;
    closeDatePushes: bigint;
    lastActivityDate: bigint;
    expectedCloseDate: bigint;
    stage: _DealStage;
    notes: string;
    account: string;
    activityLast30Days: bigint;
    amount: bigint;
}): {
    id: bigint;
    activityPrior30Days: bigint;
    owner: string;
    stakeholders: Array<Stakeholder>;
    name: string;
    createdDate: bigint;
    closeDatePushes: bigint;
    lastActivityDate: bigint;
    expectedCloseDate: bigint;
    stage: DealStage;
    notes: string;
    account: string;
    activityLast30Days: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        activityPrior30Days: value.activityPrior30Days,
        owner: value.owner,
        stakeholders: from_candid_vec_n15(_uploadFile, _downloadFile, value.stakeholders),
        name: value.name,
        createdDate: value.createdDate,
        closeDatePushes: value.closeDatePushes,
        lastActivityDate: value.lastActivityDate,
        expectedCloseDate: value.expectedCloseDate,
        stage: from_candid_DealStage_n22(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        account: value.account,
        activityLast30Days: value.activityLast30Days,
        amount: value.amount
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _StakeholderRole;
    lastContacted: bigint;
    engagement: _EngagementLevel;
}): {
    name: string;
    role: StakeholderRole;
    lastContacted: bigint;
    engagement: EngagementLevel;
} {
    return {
        name: value.name,
        role: from_candid_StakeholderRole_n18(_uploadFile, _downloadFile, value.role),
        lastContacted: value.lastContacted,
        engagement: from_candid_EngagementLevel_n20(_uploadFile, _downloadFile, value.engagement)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n37(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n41(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    signals: Array<_RiskSignal>;
    explanation: string;
    dealId: bigint;
    score: number;
    recommendedAction: string;
    topReason: string;
    bucket: _RiskBucket;
    explanationGeneratedAt: [] | [bigint];
}): {
    signals: Array<RiskSignal>;
    explanation: string;
    dealId: bigint;
    score: number;
    recommendedAction: string;
    topReason: string;
    bucket: RiskBucket;
    explanationGeneratedAt?: bigint;
} {
    return {
        signals: value.signals,
        explanation: value.explanation,
        dealId: value.dealId,
        score: value.score,
        recommendedAction: value.recommendedAction,
        topReason: value.topReason,
        bucket: from_candid_RiskBucket_n47(_uploadFile, _downloadFile, value.bucket),
        explanationGeneratedAt: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.explanationGeneratedAt))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: bigint;
    byOwner: Array<_ForecastBreakdown>;
    computedAt: bigint;
    rationaleGeneratedAt: [] | [bigint];
    high: bigint;
    byRiskBucket: Array<_ForecastBreakdown>;
    byStage: Array<_ForecastBreakdown>;
    confidenceLabel: string;
    rangeBasis: string;
    rationale: string;
    naivePipeline: bigint;
    repCommitEstimate: bigint;
    mostLikely: bigint;
}): {
    low: bigint;
    byOwner: Array<ForecastBreakdown>;
    computedAt: bigint;
    rationaleGeneratedAt?: bigint;
    high: bigint;
    byRiskBucket: Array<ForecastBreakdown>;
    byStage: Array<ForecastBreakdown>;
    confidenceLabel: string;
    rangeBasis: string;
    rationale: string;
    naivePipeline: bigint;
    repCommitEstimate: bigint;
    mostLikely: bigint;
} {
    return {
        low: value.low,
        byOwner: value.byOwner,
        computedAt: value.computedAt,
        rationaleGeneratedAt: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.rationaleGeneratedAt)),
        high: value.high,
        byRiskBucket: value.byRiskBucket,
        byStage: value.byStage,
        confidenceLabel: value.confidenceLabel,
        rangeBasis: value.rangeBasis,
        rationale: value.rationale,
        naivePipeline: value.naivePipeline,
        repCommitEstimate: value.repCommitEstimate,
        mostLikely: value.mostLikely
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forecastErrorPct: number;
    overallWinRate: number;
    avgDealCycleDays: number;
    stageStats: Array<_StageStats>;
    closedDealCount: bigint;
}): {
    forecastErrorPct: number;
    overallWinRate: number;
    avgDealCycleDays: number;
    stageStats: Array<StageStats>;
    closedDealCount: bigint;
} {
    return {
        forecastErrorPct: value.forecastErrorPct,
        overallWinRate: value.overallWinRate,
        avgDealCycleDays: value.avgDealCycleDays,
        stageStats: from_candid_vec_n56(_uploadFile, _downloadFile, value.stageStats),
        closedDealCount: value.closedDealCount
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalValue: bigint;
    weightedValue: bigint;
    stage: _DealStage;
    dealCount: bigint;
    avgDaysInStage: number;
    winRate: number;
}): {
    totalValue: bigint;
    weightedValue: bigint;
    stage: DealStage;
    dealCount: bigint;
    avgDaysInStage: number;
    winRate: number;
} {
    return {
        totalValue: value.totalValue,
        weightedValue: value.weightedValue,
        stage: from_candid_DealStage_n22(_uploadFile, _downloadFile, value.stage),
        dealCount: value.dealCount,
        avgDaysInStage: value.avgDaysInStage,
        winRate: value.winRate
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Deal;
} | {
    err: _PipelineError;
}): {
    __kind__: "ok";
    ok: Deal;
} | {
    __kind__: "err";
    err: PipelineError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Deal_n13(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PipelineError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    economicBuyer: null;
} | {
    blocker: null;
} | {
    procurement: null;
} | {
    champion: null;
} | {
    technicalEvaluator: null;
}): StakeholderRole {
    return "economicBuyer" in value ? StakeholderRole.economicBuyer : "blocker" in value ? StakeholderRole.blocker : "procurement" in value ? StakeholderRole.procurement : "champion" in value ? StakeholderRole.champion : "technicalEvaluator" in value ? StakeholderRole.technicalEvaluator : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
}): EngagementLevel {
    return "low" in value ? EngagementLevel.low : "high" in value ? EngagementLevel.high : "none" in value ? EngagementLevel.none : "medium" in value ? EngagementLevel.medium : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prospecting: null;
} | {
    closedWon: null;
} | {
    proposal: null;
} | {
    negotiation: null;
} | {
    qualification: null;
} | {
    closedLost: null;
}): DealStage {
    return "prospecting" in value ? DealStage.prospecting : "closedWon" in value ? DealStage.closedWon : "proposal" in value ? DealStage.proposal : "negotiation" in value ? DealStage.negotiation : "qualification" in value ? DealStage.qualification : "closedLost" in value ? DealStage.closedLost : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notAuthorized: null;
} | {
    invalidInput: string;
} | {
    notFound: bigint;
}): {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: bigint;
} {
    return "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _PipelineError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: PipelineError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PipelineError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DealRisk;
} | {
    err: _PipelineError;
}): {
    __kind__: "ok";
    ok: DealRisk;
} | {
    __kind__: "err";
    err: PipelineError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DealRisk_n45(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PipelineError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): RiskBucket {
    return "low" in value ? RiskBucket.low : "high" in value ? RiskBucket.high : "medium" in value ? RiskBucket.medium : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Forecast;
} | {
    err: _PipelineError;
}): {
    __kind__: "ok";
    ok: Forecast;
} | {
    __kind__: "err";
    err: PipelineError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Forecast_n52(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PipelineError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Stakeholder>): Array<Stakeholder> {
    return value.map((x)=>from_candid_Stakeholder_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StageStats>): Array<StageStats> {
    return value.map((x)=>from_candid_StageStats_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DealRisk>): Array<DealRisk> {
    return value.map((x)=>from_candid_DealRisk_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Deal>): Array<Deal> {
    return value.map((x)=>from_candid_Deal_n13(_uploadFile, _downloadFile, x));
}
function to_candid_DealStage_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): _DealStage {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Deal_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Deal): _Deal {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_EngagementLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementLevel): _EngagementLevel {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_StakeholderRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeholderRole): _StakeholderRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Stakeholder_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stakeholder): _Stakeholder {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityPrior30Days: bigint;
    owner: string;
    stakeholders: Array<Stakeholder>;
    name: string;
    createdDate: bigint;
    closeDatePushes: bigint;
    lastActivityDate: bigint;
    expectedCloseDate: bigint;
    stage: DealStage;
    notes: string;
    account: string;
    activityLast30Days: bigint;
    amount: bigint;
}): {
    id: bigint;
    activityPrior30Days: bigint;
    owner: string;
    stakeholders: Array<_Stakeholder>;
    name: string;
    createdDate: bigint;
    closeDatePushes: bigint;
    lastActivityDate: bigint;
    expectedCloseDate: bigint;
    stage: _DealStage;
    notes: string;
    account: string;
    activityLast30Days: bigint;
    amount: bigint;
} {
    return {
        id: value.id,
        activityPrior30Days: value.activityPrior30Days,
        owner: value.owner,
        stakeholders: to_candid_vec_n30(_uploadFile, _downloadFile, value.stakeholders),
        name: value.name,
        createdDate: value.createdDate,
        closeDatePushes: value.closeDatePushes,
        lastActivityDate: value.lastActivityDate,
        expectedCloseDate: value.expectedCloseDate,
        stage: to_candid_DealStage_n31(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        account: value.account,
        activityLast30Days: value.activityLast30Days,
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: StakeholderRole;
    lastContacted: bigint;
    engagement: EngagementLevel;
}): {
    name: string;
    role: _StakeholderRole;
    lastContacted: bigint;
    engagement: _EngagementLevel;
} {
    return {
        name: value.name,
        role: to_candid_StakeholderRole_n7(_uploadFile, _downloadFile, value.role),
        lastContacted: value.lastContacted,
        engagement: to_candid_EngagementLevel_n9(_uploadFile, _downloadFile, value.engagement)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EngagementLevel): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
} {
    return value == EngagementLevel.low ? {
        low: null
    } : value == EngagementLevel.high ? {
        high: null
    } : value == EngagementLevel.none ? {
        none: null
    } : value == EngagementLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DealStage): {
    prospecting: null;
} | {
    closedWon: null;
} | {
    proposal: null;
} | {
    negotiation: null;
} | {
    qualification: null;
} | {
    closedLost: null;
} {
    return value == DealStage.prospecting ? {
        prospecting: null
    } : value == DealStage.closedWon ? {
        closedWon: null
    } : value == DealStage.proposal ? {
        proposal: null
    } : value == DealStage.negotiation ? {
        negotiation: null
    } : value == DealStage.qualification ? {
        qualification: null
    } : value == DealStage.closedLost ? {
        closedLost: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StakeholderRole): {
    economicBuyer: null;
} | {
    blocker: null;
} | {
    procurement: null;
} | {
    champion: null;
} | {
    technicalEvaluator: null;
} {
    return value == StakeholderRole.economicBuyer ? {
        economicBuyer: null
    } : value == StakeholderRole.blocker ? {
        blocker: null
    } : value == StakeholderRole.procurement ? {
        procurement: null
    } : value == StakeholderRole.champion ? {
        champion: null
    } : value == StakeholderRole.technicalEvaluator ? {
        technicalEvaluator: null
    } : value;
}
function to_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Stakeholder>): Array<_Stakeholder> {
    return value.map((x)=>to_candid_Stakeholder_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
